#pragma once

constexpr int Error = -1;	//エラー告知

constexpr int nZeroSize = 0;	//サイズ０

constexpr float fJump_v0 = 7.0f;	//ジャンプ力
constexpr float fGravity = -0.2f;	//重力
constexpr float fInitGravity = 0.0f;	//重力（初期化時）
constexpr float fNonGravity = 0.0f;	//重力ゼロ値にしたいとき
constexpr float fNonSpeed = 0.0f;	//速度０にしたいとき
constexpr int nZeroLife = 0;	//ライフが０の時
constexpr int nLoiterningMoveMaxEnemy = 20;	//徘徊する敵の数
constexpr int nTrackingMoveMaxEnemy = 20;	//追尾する敵の数
constexpr int nTurnMoveMaxEnemy = 20;	//左右に移動する敵の数
constexpr int nTotalMaxEnemy = 60;	//トータルの敵の数
constexpr float fBulletSpeed = 17.5f;	//弾速
constexpr float fBulletInitSpeed = 0.0f;	//初期化時の弾速
constexpr float fBulletScale = 12.0f;	//弾の大きさ
constexpr int nBulletInitCount = 0;	//初期化時の弾の数
constexpr int nBulletInitNumber = 0;	//弾番号0番
constexpr int nBulletInitType = 0;	//弾の種類
constexpr int nBulletMaxCount = 10;	//弾の最大数
constexpr int nBulletNonCount = 0;	//弾の最小数
constexpr int nBulletDeadMaxCount = 30;	//弾が消えるまでの最大時間
constexpr float fDefaultPos = 0.0f;	//初期位置
constexpr bool bInitShake = false;	//振動
constexpr float fCharacterShakePower = 2.5f;	//キャラクターを振動させるときの強さ

constexpr int nMaxMoveFrame = 3;	//移動キーフレーム最大値
constexpr int nInitMoveFrame = 0;	//移動フレーム（初期化時）
constexpr int nInitAttackFrame = 0;	//攻撃時のフレーム（初期化時）
constexpr int nInitSideAttackFrame = 0;	//着地した状態で両サイドで攻撃開始させたときのフレーム（初期化時）
constexpr int nGravityFrame = 5;	//重力が発動するフレーム数
constexpr int nShakeFrame = 2;	//攻撃が発動するフレーム数

constexpr int nInitCharacterActionState = 0;	//キャラクター行動パターン（初期化時）
constexpr int nCharacterLife = 5;	//キャラクターの初期化時のHP
constexpr int nCharacterSize = 16;	//キャラクター画像の大きさ
constexpr int nInitCharacterHitCoolTime = 0;	//キャラクターがヒット判定になった時にカウントされる変数の初期化用
constexpr bool bInitInvincible = false;	//キャラクターの無敵フラグ(初期化時）
constexpr bool bInitHitEnemy = false;	//プレイヤーが敵にヒットする時の判定（初期化時）
constexpr bool bInitLeftDamage = false;	//プレイヤーの右側面の衝突判定（初期化時）
constexpr bool bInitRightDamage = false;	//プレイヤーの左側面の衝突判定（初期化時)
constexpr bool bInitDamage = false;	//ダメージフラグの初期化
constexpr bool bInitCharacterJump = false;	//キャラクターのジャンプフラグ（初期化時）
constexpr bool bInitAttack = false;	//攻撃フラグ（初期化時）
constexpr int nCharacterJumping = 0;	//キャラクターがジャンプするときのステート
constexpr int nCharacterAttackJumping = 1;	//キャラクターがジャンプしているときのステート
constexpr float fAddGravity = 0.4f;	//重力に加える数値
constexpr bool bInitBulletJump = false;	//攻撃中のジャンプフラグ（初期化時）
constexpr bool bInitJump = false;	//ジャンプ中のフラグ（初期化時）
constexpr int nInitSideType = -1;	//キャラクターの左右移動フラグ（初期化時）
constexpr int nInitLeftAcceleration = -1;	//左移動時のステート（初期化時）
constexpr int nInitRightAcceleration = -1;	//右移動時のステート（初期化時）
constexpr int nFirstAcceleration = 0;	//加速1段階
constexpr int nSecondAcceleration = 1;	//加速2段階
constexpr float fFirstAccelerationSpeed = 1.0f;
constexpr float fSecondAccelerationSpeed = 3.0f;
constexpr int nGameLeftLine = 175;	//左の移動可動域
constexpr int nGameRightLine = 505;	//右の移動可動域
constexpr float fCameraLeftLine = 150.0f;
constexpr float fCameraRightLine = 550.0f;
constexpr int nLeftType = 0;	//左ステート番号
constexpr int nRightType = 1;	//右ステート番号

constexpr int nQuadTreeMaxCount = 4;	//クアッドツリーの枠数
constexpr int nInitEnemyMoveType = 0;	//敵の移動ステート（初期化時）
constexpr bool bInitEnemyLife = true;	//敵の生存フラグ（初期化時）
constexpr bool bInitEnemyHitAction = false;	//敵の衝突判定（初期化時）
constexpr bool bInitActive = false;	//敵のアクティブフラグ（初期化時）
constexpr float fBirdRectPadding = 9.0f;	//鳥の中心座標からの幅
constexpr float fBirdTextureScale = 18.0f;	//鳥画像の大きさ
constexpr float fUrchinRectPadding = 8.0f;	//ウニの中心座標からの幅
constexpr float fUrchinTextureScale = 16.0f;	//ウニ画像の大きさ
constexpr float fTurtleRectPadding = 9.0f;	//亀の中心座標からの幅
constexpr float fTurtleTextureScale = 18.0f;	//亀画像の大きさ
constexpr int nInitStageLevelNumber = 0;	//ステージクラスの初期化時のレベル番号
constexpr int nInitBlockSideBlockTexture = 0;	//ステージ画像の初期化
constexpr int nInitNonBlockTexture = 0;	//ステージ画像の初期化
constexpr int nInitSideBlockTexture = 0;	//ステージ画像の初期化
constexpr int nInitBlockTexture = 0;	//ステージ画像の初期化
constexpr int nInitInSideBlockTexture = 0;	//ステージ画像の初期化
constexpr int nInitNotBrokenBlockTexture = 0;	//ステージ画像の初期化
constexpr int nAreaMax = 7;	//描画するエリアの最大数
constexpr int nBackGroundType = 0;	//背景ブロックの番号
constexpr int nMoveBlockType = 1;	//移動不可ブロックの番号
constexpr int nFloatingBlockType = 2;
constexpr int nBlokenBlockType = 3;
constexpr int nSideBlockType = 4;
constexpr int nInSideBlockType = 5;
constexpr int nLeftChangeType = 7;	//左に反転するブロック番号
constexpr int nRightChangeType = 8;	//右に反転するブロック番号
constexpr int nGoalType = 6;	//ゴールブロックの番号
constexpr int nTitleLevel = 0;	//タイトルレベル
constexpr int nGameLevel = 1;	//ゲームレベル
constexpr int nResultLevel = 2;	//リザルトレベル
constexpr int nMaxLevel = 3;	//レベルの最大値
constexpr int nInitBulletTexture = 0;	//弾テクスチャー（初期化時）
constexpr int nInitNonBulletTexture = 0;	//残弾が空になった時のテクスチャー（初期化時）
constexpr double dMinDis = 0.0;	//(乱数最小値)
constexpr double dMaxDis = 1.0;	//(乱数最大値)

constexpr int nFirstStage = 1;	//第一区画
constexpr int nStageMaxCount = 12;	//ステージ区画
constexpr int nStageHeight = 50;	//ステージ高さ
constexpr int nStageWidth = 20;		//ステージ幅